### ISSUE TITLE
Pydantic Error

### ISSUE THREAD

**Issue by jondoescoding** [ju-bezdek/langchain-decorators#7]
Hey! I'm currently getting the following error:
ImportError: cannot import name 'ModelField' from 'pydantic.fields' 

I suppose it has to do with the recent release of pydantic 2.0 but I'm not sure.

**Comment by ju-bezdek** [comment]
Yes, im pretty sure it will be caused by pydantic 2.0 as there were pretty big breaking changes...  

Im was planning to support pydantic 2.0 but I'm not yes sure whether it will be possible to make it compatible with both versions up until recently v1 was still dominating

In the meantime, do you need v2 or can you downgrade do v1?

**Comment by ju-bezdek** [comment]
hotfixed with v0.2.0

... though I'm not sure what would happen if you'd use a model defined by pydantic-v2  as an output type
